### ISSUE TITLE
Docs, examples or screenshots

### ISSUE THREAD

**Issue by peter-lyons-kehl** [lxw15337674/vscode-extension-switch-tab#1]
Hi bhwa233,

`vscode-extension-switch-tab` seems interesting. However, its goal and usage are unclear.

1. I understand that I need to set up key shortcuts myself. But where and how?
2. What does "mark a tab" mean? Can there be several tabs marked at the same time, or only one?
3. May I suggest that you put a link from `README.md` to https://marketplace.visualstudio.com/items?itemName=bhwa233.switch-tab, so that if someone finds this on GitHub, the link points them to the marketplace.

**Comment by lxw15337674** [comment]
Thanks for your issue. I will update  README.
